CREATE TABLE USUARIO (
  idUSUARIO INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  Apodo VARCHAR(20) NOT NULL,
  Contrasenia VARCHAR(20) NOT NULL,
  PRIMARY KEY(idUSUARIO)
);

CREATE TABLE GRUPOS (
  idGRUPOS INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  Dueño VARCHAR(20) NULL,
  NombreGrupo VARCHAR(45) NULL,
  PRIMARY KEY(idGRUPOS)
);

CREATE TABLE DATOS (
  idDATOS INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  USUARIO_idUSUARIO INTEGER UNSIGNED NOT NULL,
  Nombre VARCHAR(45) NULL,
  Apellido1 VARCHAR(45) NULL,
  Apellido2 VARCHAR(45) NULL,
  Email VARCHAR(255) NULL,
  PRIMARY KEY(idDATOS),
  INDEX DATOS_FKIndex1(USUARIO_idUSUARIO),
  FOREIGN KEY(USUARIO_idUSUARIO)
    REFERENCES USUARIO(idUSUARIO)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE LISTAS (
  idLISTAS INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  USUARIO_idUSUARIO INTEGER UNSIGNED NOT NULL,
  NombreLista VARCHAR(20) NULL,
  PRIMARY KEY(idLISTAS),
  INDEX LISTAS_FKIndex1(USUARIO_idUSUARIO),
  FOREIGN KEY(USUARIO_idUSUARIO)
    REFERENCES USUARIO(idUSUARIO)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE MIEMBROS (
  USUARIO_idUSUARIO INTEGER UNSIGNED NOT NULL,
  GRUPOS_idGRUPOS INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY(USUARIO_idUSUARIO, GRUPOS_idGRUPOS),
  INDEX USUARIO_has_GRUPOS_FKIndex1(USUARIO_idUSUARIO),
  INDEX USUARIO_has_GRUPOS_FKIndex2(GRUPOS_idGRUPOS),
  FOREIGN KEY(USUARIO_idUSUARIO)
    REFERENCES USUARIO(idUSUARIO)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(GRUPOS_idGRUPOS)
    REFERENCES GRUPOS(idGRUPOS)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE TAREAS (
  idTAREAS INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  LISTAS_idLISTAS INTEGER UNSIGNED NOT NULL,
  NombreTarea VARCHAR(45) NOT NULL,
  Descripcion VARCHAR(255) NULL,
  Chequeo BOOL NULL,
  PRIMARY KEY(idTAREAS),
  INDEX TAREAS_FKIndex1(LISTAS_idLISTAS),
  FOREIGN KEY(LISTAS_idLISTAS)
    REFERENCES LISTAS(idLISTAS)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE SUBTAREAS (
  idSUBTAREAS INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  TAREAS_idTAREAS INTEGER UNSIGNED NOT NULL,
  NombreSTarea VARCHAR(45) NULL,
  DescripcionST VARCHAR(255) NULL,
  ChequeoST BOOL NULL,
  PRIMARY KEY(idSUBTAREAS),
  INDEX SUBTAREAS_FKIndex1(TAREAS_idTAREAS),
  FOREIGN KEY(TAREAS_idTAREAS)
    REFERENCES TAREAS(idTAREAS)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);


